version: "3.8"
services:
#  db:
#    build:
#      dockerfile: Dockerfile
#      context: .
#    depends_on:
#      - postgres
#    environment:
#      DATABASE_URL: postgres://user:password@postgres:5432/tasks_db
#      NODE_ENV: development
#    ports:
#      - "3000:3000"

  postgres:
    image: postgres:10.4
    ports:
      - "5454:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tasks_db